apiVersion: v1
kind: Service
metadata:
  name: wave-lab-app
spec:
  type: ClusterIP
  selector:
    app: wave-lab-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
